version: '3.8'
name: liaison-platform

services:
  # Frontend - No-Code Chatbot Builder
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
      - NEXT_PUBLIC_BLOCKCHAIN_RPC=http://localhost:8545
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - liaison-network

  # Backend API - Core Platform Logic
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/liaison
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=development
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - liaison-network

  # Chatbot Runtime - AI Processing Engine
  chatbot-runtime:
    build: ./chatbot-runtime
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://postgres:password@db:5432/liaison
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./chatbot-runtime:/app
      - /app/node_modules
    networks:
      - liaison-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=liaison
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - liaison-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - liaison-network

  # Template Marketplace (Optional - for NFT features)
  marketplace:
    build: ./marketplace
    ports:
      - "6000:6000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/liaison
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
    depends_on:
      - db
    volumes:
      - ./marketplace:/app
      - /app/node_modules
    networks:
      - liaison-network

  # NGINX Load Balancer (Production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - liaison-network

volumes:
  postgres_data:
  redis_data:

networks:
  liaison-network:
    driver: bridge